#! /bin/bash

if [ $# -eq 0 ]; then
	echo -e "\e[31mVeuillez passer un argument !\e[0m"
elif [ -f /var/docs/"$1".md ]; then
	mdp /var/docs/"$1".md;
else
	echo -e "\e[31mAide non disponible pour \e[4m$@\e[0m \e[31m!\e[0m"
fi
